/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;

/**
 *
 * @author deva
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    User user;
    public CreateJPanel(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextfirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextlastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTexttelephoneNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextstreetLine1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextstreetLine2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextcity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextcountry = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextaffiliation = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextmajor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextcareer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextdegree1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextdegree2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jTextdob = new com.toedter.calendar.JDateChooser();
        jTextdegree1Start = new com.toedter.calendar.JDateChooser();
        jTextdegree1End = new com.toedter.calendar.JDateChooser();
        jTextdegree2End = new com.toedter.calendar.JDateChooser();
        jTextdegree2Start = new com.toedter.calendar.JDateChooser();
        jUploadBtn = new javax.swing.JButton();
        jUploadedFileName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel11.setText("DOB");

        setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel3.setText("First Name");

        jTextfirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfirstNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name");

        jTextlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextlastNameActionPerformed(evt);
            }
        });

        jLabel5.setText("DOB");

        jLabel6.setText("Age");

        jTextage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextageActionPerformed(evt);
            }
        });

        jLabel7.setText("Telephone Number");

        jTexttelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttelephoneNoActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jTextemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextemailActionPerformed(evt);
            }
        });

        jLabel10.setText("Street Line 1");

        jTextstreetLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextstreetLine1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Street Line 2");

        jTextstreetLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextstreetLine2ActionPerformed(evt);
            }
        });

        jLabel13.setText("City");

        jTextcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcityActionPerformed(evt);
            }
        });

        jLabel14.setText("Country");

        jTextcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcountryActionPerformed(evt);
            }
        });

        jLabel15.setText("Affiliation");

        jTextaffiliation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextaffiliationActionPerformed(evt);
            }
        });

        jLabel16.setText("Major");

        jTextmajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextmajorActionPerformed(evt);
            }
        });

        jLabel17.setText("Career");

        jTextcareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcareerActionPerformed(evt);
            }
        });

        jLabel18.setText("Degree 1");

        jTextdegree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdegree1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Degree 1 Start");

        jLabel20.setText("Degree 1 End");

        jLabel21.setText("Degree 2");

        jTextdegree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdegree2ActionPerformed(evt);
            }
        });

        jLabel22.setText("Degree 2 Start");

        jLabel23.setText("Degree 2 End");

        jLabel24.setText("Photo");

        saveBtn.setBackground(new java.awt.Color(63, 81, 181));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jUploadBtn.setText("Upload");
        jUploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Create User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextstreetLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextcity, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextaffiliation, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextcareer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextdegree2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextdob, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTexttelephoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextdegree1Start, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jTextdegree2End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextfirstName))
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUploadedFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextage)
                            .addComponent(jTextemail)
                            .addComponent(jTextstreetLine2)
                            .addComponent(jTextcountry)
                            .addComponent(jTextmajor)
                            .addComponent(jTextdegree1)
                            .addComponent(jTextdegree1End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextdegree2Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextlastName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jUploadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel13, jLabel15, jLabel17, jLabel19, jLabel21, jLabel23, jLabel3, jLabel5, jLabel7, jTextaffiliation, jTextcareer, jTextcity, jTextdegree1Start, jTextdegree2, jTextdegree2End, jTextdob, jTextstreetLine1, jTexttelephoneNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel14, jLabel16, jLabel18, jLabel20, jLabel22, jLabel24, jLabel4, jLabel6, jLabel8, jTextage, jTextcountry, jTextdegree1, jTextdegree1End, jTextdegree2Start, jTextemail, jTextlastName, jTextmajor, jTextstreetLine2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTexttelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextstreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextaffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree1Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree2End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextstreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextmajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree1End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextdegree2Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUploadBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUploadedFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel13, jLabel15, jLabel17, jLabel19, jLabel21, jLabel3, jLabel5, jLabel7, jTextaffiliation, jTextcareer, jTextcity, jTextdegree1Start, jTextdegree2, jTextdegree2End, jTextdob, jTextfirstName, jTextstreetLine1, jTexttelephoneNo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel14, jLabel16, jLabel18, jLabel20, jLabel22, jLabel24, jLabel4, jLabel6, jLabel8, jTextage, jTextcountry, jTextdegree1, jTextdegree1End, jTextdegree2Start, jTextemail, jTextlastName, jTextmajor, jTextstreetLine2});

    }// </editor-fold>//GEN-END:initComponents

    private void jTextfirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfirstNameActionPerformed

    private void jTextlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextlastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextlastNameActionPerformed

    private void jTextageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextageActionPerformed

    private void jTexttelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttelephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttelephoneNoActionPerformed

    private void jTextemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextemailActionPerformed

    private void jTextstreetLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextstreetLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextstreetLine1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextstreetLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextstreetLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextstreetLine2ActionPerformed

    private void jTextcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcityActionPerformed

    private void jTextcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcountryActionPerformed

    private void jTextaffiliationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextaffiliationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextaffiliationActionPerformed

    private void jTextmajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextmajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextmajorActionPerformed

    private void jTextcareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcareerActionPerformed

    private void jTextdegree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdegree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdegree1ActionPerformed

    private void jTextdegree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdegree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdegree2ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
        
        
        user.setFirstName(jTextfirstName.getText());
        user.setLastName(jTextlastName.getText());
        String dateDob = dateFormat.format(jTextdob.getDate());
        user.setDob(dateDob);
        user.setAge(jTextage.getText());
        user.setTelephoneNo(jTexttelephoneNo.getText());
        user.setEmail(jTextemail.getText());
        user.setStreetLine1(jTextstreetLine1.getText());
        user.setStreetLine2(jTextstreetLine2.getText());
        user.setCity(jTextcity.getText());
        user.setCountry(jTextcountry.getText());
        user.setAffiliation(jTextaffiliation.getText());
        user.setMajor(jTextmajor.getText());
        user.setCareer(jTextcareer.getText());
        user.setDegree1(jTextdegree1.getText());
        String dateDegree1Start = dateFormat.format(jTextdegree1Start.getDate());
        user.setDegree1Start(dateDegree1Start);
        String dateDegree1End = dateFormat.format(jTextdegree1End.getDate());
        user.setDegree1End(dateDegree1End);
        user.setDegree2(jTextdegree2.getText());
        String dateDegree2Start = dateFormat.format(jTextdegree2Start.getDate());
        user.setDegree2Start(dateDegree2Start);
        String dateDegree2End = dateFormat.format(jTextdegree2End.getDate());
        user.setDegree2End(dateDegree2End);
//        user.setPhoto(jTextphoto.getText()); 
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jUploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadBtnActionPerformed
        // TODO add your handling code here:
        String filename = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File selectedFile = fileChooser.getSelectedFile();
        user.setPhoto(selectedFile); 
        filename = selectedFile.getAbsolutePath();
        jUploadedFileName.setText(filename);
    }//GEN-LAST:event_jUploadBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextaffiliation;
    private javax.swing.JTextField jTextage;
    private javax.swing.JTextField jTextcareer;
    private javax.swing.JTextField jTextcity;
    private javax.swing.JTextField jTextcountry;
    private javax.swing.JTextField jTextdegree1;
    private com.toedter.calendar.JDateChooser jTextdegree1End;
    private com.toedter.calendar.JDateChooser jTextdegree1Start;
    private javax.swing.JTextField jTextdegree2;
    private com.toedter.calendar.JDateChooser jTextdegree2End;
    private com.toedter.calendar.JDateChooser jTextdegree2Start;
    private com.toedter.calendar.JDateChooser jTextdob;
    private javax.swing.JTextField jTextemail;
    private javax.swing.JTextField jTextfirstName;
    private javax.swing.JTextField jTextlastName;
    private javax.swing.JTextField jTextmajor;
    private javax.swing.JTextField jTextstreetLine1;
    private javax.swing.JTextField jTextstreetLine2;
    private javax.swing.JTextField jTexttelephoneNo;
    private javax.swing.JButton jUploadBtn;
    private javax.swing.JLabel jUploadedFileName;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
